version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_app
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
