version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"      # HTTP
      #- "443:443"    # HTTPS (uncomment if SSL is configured)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./ssl:/etc/nginx/ssl  # Uncomment for SSL certificates
    depends_on:
      - frontend
      - backend
    restart: always

  # React Frontend (Vite)
  frontend:
    build: ./frontend
    container_name: react-frontend
    # ports:
      # - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
    restart: always

  # Django Backend
  backend:
    build: ./backend
    container_name: django-backend
    # ports:
      # - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=0
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"